language: php

php: '7.2'

os: linux

dist: xenial

git:
  quiet: true
  depth: 3

env:
  global:
    - MEDIAWIKI_BRANCH=REL1_31
    # Maximum iteration limit for loop
    - LOOP_LIMIT=300

cache:
  directories:
  - vendor

services:
  - docker

jobs:
  include:
    - name: lint
      before_script:
        - composer install --prefer-source --quiet --no-interaction
      script:
        - composer test
    - name: docker
      before_script:
        # Setup files for database and memcached
        - git clone https://github.com/femiwiki/database.git ~/swarm --depth=1
        - sudo mkdir -p /srv/mysql/
        # Prepare configuration files
        - cp configs/env.example configs/env
        - cp configs/secret.php.example configs/secret.php
        # Tweak LocalSettings.php for debugging
        - echo -en "\n\nwfRunDebugMode( 'localhost' );\n" >> configs/LocalSettings.php
        - echo -en '\n\nrequire_once "$IP/includes/DevelopmentSettings.php";\n' >> configs/LocalSettings.php
        # Initialize docker swarm
        - docker swarm init
        # Start up database
        - docker stack deploy -c ~/swarm/database.yml database
        # We need root password of the database, so wait for the generation
        - |
            printf 'Waiting for database_mysql service...';
            # Set counter to check endless loop
            COUNTER=0;
            while [ -z $(docker service logs database_mysql 2>&1 | grep -oP 'GENERATED ROOT PASSWORD: \K.+') ]; do
              # retry every 1 second.
              sleep 1;
              # Append dots to the previous message if process is delayed.
              printf '.';
              # Terminate Travis-ci if loop exceeds limit
              (( COUNTER++ ));
              if [ $COUNTER -gt $LOOP_LIMIT ]; then
                printf '\n';
                echo 'Falied to start database_mysql service';
                # Print logs for debugging
                docker service logs database_mysql;
                travis_terminate 1;
              fi
            done; printf '\n'
        # Start up memcached
        - docker stack deploy -c ~/swarm/memcached.yml memcached
        # Configure mediawiki
        - HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
        - MYSQL_USER=root
        - "MYSQL_PW=$(docker service logs database_mysql 2>&1 | grep -Po 'GENERATED ROOT PASSWORD: \\K.+')"
        - sed -ri "s/mysqlhostname/${HOST_IP}/" configs/env
        - sed -ri "s/mysqlusername/${MYSQL_USER}/" configs/env
        - sed -ri "s/mysqlpassword/${MYSQL_PW}/" configs/env
        - sed -ri "s/DB_HOSTNAME/${HOST_IP}/" configs/secret.php
        - sed -ri "s/DB_USERNAME/${MYSQL_USER}/" configs/secret.php
        - sed -ri "s/DB_PASSWORD/${MYSQL_PW}/" configs/secret.php
        - sed -ri "s/MEMCACHED_HOSTNAME/${HOST_IP}/" configs/secret.php
      script:
        - docker build --tag femiwiki/mediawiki .
        - docker stack deploy -c docker-compose.yml mediawiki
        # We don't have a health check yet, so wait a moment for starting process is end...
        - sleep 60
        - docker service logs mediawiki_fastcgi
        # Check if container is shoutdown
        - test -z "$(docker service ps -qf "desired-state=Shutdown" mediawiki_fastcgi)"
        # Access localhost until success
        - |
            printf 'Waiting for http...'
            COUNTER=0;
            until [ "$(curl -Lfs localhost)" ]; do
              sleep 1;
              printf '.';
              (( COUNTER++ ));
              if [ $COUNTER -gt $LOOP_LIMIT ]; then
                printf '\n';
                echo 'Failed to connect to localhost';
                travis_terminate 1;
              fi
            done; printf '\n'
        - curl -Lf localhost | head
