os: linux
dist: xenial
git:
  quiet: true
  depth: 3

# PHP
language: php
php: '7.2'
cache:
  directories:
    - vendor

env:
  global:
    # Maximum iteration limit for loop
    - LOOP_LIMIT=300

services:
  - docker

jobs:
  include:
    #
    # LocalSettings.php 코드 lint
    #
    - name: lint
      before_script:
        - composer install --prefer-source --quiet --no-interaction
      script:
        - composer test


    #
    # 미디어위키 도커 이미지가 정상적으로 실행되는지 확인
    #
    - name: docker
      before_script:
        # Setup files for database and memcached
        - git clone https://github.com/femiwiki/database.git ~/swarm --depth=1
        - sudo mkdir -p /srv/mysql/
        # Initialize docker swarm and start memcached and MySQL
        - docker swarm init
        - docker stack deploy -c ~/swarm/memcached.yml memcached
        - docker stack deploy -c ~/swarm/database.yml database
      script:
        # Build image
        - docker build --tag femiwiki/mediawiki .
        # Wait until root account's password of MySQL is generated
        - |
          printf 'Waiting for database_mysql service...';
          # Set counter to check endless loop
          COUNTER=0;
          while [ -z $(docker service logs database_mysql 2>&1 | grep -oP 'GENERATED ROOT PASSWORD: \K.+') ]; do
            # retry every 1 second.
            sleep 1;
            # Append dots to the previous message if process is delayed.
            printf '.';
            # Terminate Travis-ci if loop exceeds limit
            (( COUNTER++ ));
            if [ $COUNTER -gt $LOOP_LIMIT ]; then
              printf '\n';
              echo 'Falied to start database_mysql service';
              # Print logs for debugging
              docker service logs database_mysql;
              travis_terminate 1;
            fi
          done;
          printf '\n';
        # Edit configuration
        - |
          HOST_IP="$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')";
          MYSQL_PW="$(docker service logs database_mysql 2>&1 | grep -Po 'GENERATED ROOT PASSWORD: \K.+')";
          mv configs/env.example configs/env;
          mv configs/secret.php.example configs/secret.php;
          sed -ri "s/mysqlhostname/${HOST_IP}/; s/mysqlusername/root/; s/mysqlpassword/${MYSQL_PW}/" configs/env;
          sed -ri "s/DB_HOSTNAME/${HOST_IP}/; s/DB_USERNAME/root/; s/DB_PASSWORD/${MYSQL_PW}/; s/MEMCACHED_HOSTNAME/${HOST_IP}/" configs/secret.php;
          printf 'wfRunDebugMode("localhost");\nrequire_once "$IP/includes/DevelopmentSettings.php";\n' >> configs/LocalSettings.php;
        # Start mediawiki
        - docker stack deploy -c docker-compose.yml mediawiki
        # Check if the container is still up
        - test -z "$(docker service ps -qf 'desired-state=Shutdown' mediawiki_fastcgi)"
        # Access localhost until success
        - |
            printf 'Waiting for http...'
            COUNTER=0;
            until [ "$(curl -Ls localhost 2>/dev/null)" ]; do
              sleep 1;
              printf '.';
              (( COUNTER++ ));
              if [ $COUNTER -gt $LOOP_LIMIT ]; then
                printf '\n';
                echo 'Failed to connect to localhost';
                travis_terminate 1;
              fi
            done; printf '\n'
        # Try to access the mediawiki
        - |
          curl -sSLvo /dev/null localhost || docker service logs mediawiki_fastcgi
