version: '3'
services:
  http:
    image: joshix/caddy
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/www/html:ro
  fastcgi:
    image: femiwiki/mediawiki
    volumes:
      - ./configs:/a:ro
    env_file:
      - configs/env
  cache:
    image: memcached:1-alpine
  parsoid:
    image: femiwiki/parsoid
