version: '3'
services:
  http:
    image: joshix/caddy
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/www/html:ro
      - files:/srv/femiwiki.com
  fastcgi:
    image: femiwiki/mediawiki
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
    env_file:
      - configs/fastcgi.env
  cache:
    image: memcached:1-alpine
  parsoid:
    image: femiwiki/parsoid
    env_file:
      - configs/parsoid.env
volumes:
  files:
