version: '3'
services:
  http:
    image: joshix/caddy
    ports:
      - 80:80
    volumes:
      - ./caddy:/var/www/html:ro
      - files:/srv/femiwiki.com
  fastcgi:
    image: femiwiki/mediawiki
    volumes:
      - ./configs:/a:ro
      - files:/srv/femiwiki.com
    env_file:
      - configs/env
  parsoid:
    image: femiwiki/parsoid
volumes:
  files:
